//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Net;

namespace WebRef
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", ConfigurationName="WebRef.PESALinkTransfer_Port")]
    public interface PESALinkTransfer_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer:GetEntryToTransfer", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRef.GetEntryToTransfer_Result> GetEntryToTransferAsync(WebRef.GetEntryToTransfer request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer:UpdateTransferStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRef.UpdateTransferStatus_Result> UpdateTransferStatusAsync(WebRef.UpdateTransferStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer:GetEntryToSeekStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRef.GetEntryToSeekStatus_Result> GetEntryToSeekStatusAsync(WebRef.GetEntryToSeekStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer:GetISODescription", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRef.GetISODescription_Result> GetISODescriptionAsync(WebRef.GetISODescription request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer:CheckValidAccountDetails" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRef.CheckValidAccountDetails_Result> CheckValidAccountDetailsAsync(WebRef.CheckValidAccountDetails request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer:InsertDepositEntry", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRef.InsertDepositEntry_Result> InsertDepositEntryAsync(WebRef.InsertDepositEntry request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer:GetEntryToSeekDepositSta" +
            "tus", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRef.GetEntryToSeekDepositStatus_Result> GetEntryToSeekDepositStatusAsync(WebRef.GetEntryToSeekDepositStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer:UpdateDepositStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRef.UpdateDepositStatus_Result> UpdateDepositStatusAsync(WebRef.UpdateDepositStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer:PostPESALinkDeposits", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRef.PostPESALinkDeposits_Result> PostPESALinkDepositsAsync(WebRef.PostPESALinkDeposits request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntryToTransfer", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class GetEntryToTransfer
    {
        
        public GetEntryToTransfer()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntryToTransfer_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class GetEntryToTransfer_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string return_value;
        
        public GetEntryToTransfer_Result()
        {
        }
        
        public GetEntryToTransfer_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTransferStatus", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class UpdateTransferStatus
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string requestID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=1)]
        public string statusOfRequestCode;
        
        public UpdateTransferStatus()
        {
        }
        
        public UpdateTransferStatus(string requestID, string statusOfRequestCode)
        {
            this.requestID = requestID;
            this.statusOfRequestCode = statusOfRequestCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTransferStatus_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class UpdateTransferStatus_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string return_value;
        
        public UpdateTransferStatus_Result()
        {
        }
        
        public UpdateTransferStatus_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntryToSeekStatus", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class GetEntryToSeekStatus
    {
        
        public GetEntryToSeekStatus()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntryToSeekStatus_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class GetEntryToSeekStatus_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string return_value;
        
        public GetEntryToSeekStatus_Result()
        {
        }
        
        public GetEntryToSeekStatus_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetISODescription", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class GetISODescription
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string actionCode;
        
        public GetISODescription()
        {
        }
        
        public GetISODescription(string actionCode)
        {
            this.actionCode = actionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetISODescription_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class GetISODescription_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string return_value;
        
        public GetISODescription_Result()
        {
        }
        
        public GetISODescription_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckValidAccountDetails", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class CheckValidAccountDetails
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string accountNo;
        
        public CheckValidAccountDetails()
        {
        }
        
        public CheckValidAccountDetails(string accountNo)
        {
            this.accountNo = accountNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckValidAccountDetails_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class CheckValidAccountDetails_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string return_value;
        
        public CheckValidAccountDetails_Result()
        {
        }
        
        public CheckValidAccountDetails_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDepositEntry", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class InsertDepositEntry
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string sourceReferenceNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=1)]
        public string sourceBankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=2)]
        public string sourceAccountNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=3)]
        public string sourceAccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=4)]
        public string purpose;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=5)]
        public string amountToTransfer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=6)]
        public string destinationAccountNo;
        
        public InsertDepositEntry()
        {
        }
        
        public InsertDepositEntry(string sourceReferenceNo, string sourceBankCode, string sourceAccountNo, string sourceAccountName, string purpose, string amountToTransfer, string destinationAccountNo)
        {
            this.sourceReferenceNo = sourceReferenceNo;
            this.sourceBankCode = sourceBankCode;
            this.sourceAccountNo = sourceAccountNo;
            this.sourceAccountName = sourceAccountName;
            this.purpose = purpose;
            this.amountToTransfer = amountToTransfer;
            this.destinationAccountNo = destinationAccountNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertDepositEntry_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class InsertDepositEntry_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string return_value;
        
        public InsertDepositEntry_Result()
        {
        }
        
        public InsertDepositEntry_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntryToSeekDepositStatus", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class GetEntryToSeekDepositStatus
    {
        
        public GetEntryToSeekDepositStatus()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntryToSeekDepositStatus_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class GetEntryToSeekDepositStatus_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string return_value;
        
        public GetEntryToSeekDepositStatus_Result()
        {
        }
        
        public GetEntryToSeekDepositStatus_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDepositStatus", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class UpdateDepositStatus
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string entryNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=1)]
        public string sourceReferenceNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=2)]
        public string sourceBankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=3)]
        public string sourceAccountNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=4)]
        public string amountToTransfer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=5)]
        public string destinationAccountNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=6)]
        public string responseCode;
        
        public UpdateDepositStatus()
        {
        }
        
        public UpdateDepositStatus(string entryNo, string sourceReferenceNo, string sourceBankCode, string sourceAccountNo, string amountToTransfer, string destinationAccountNo, string responseCode)
        {
            this.entryNo = entryNo;
            this.sourceReferenceNo = sourceReferenceNo;
            this.sourceBankCode = sourceBankCode;
            this.sourceAccountNo = sourceAccountNo;
            this.amountToTransfer = amountToTransfer;
            this.destinationAccountNo = destinationAccountNo;
            this.responseCode = responseCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDepositStatus_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class UpdateDepositStatus_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string return_value;
        
        public UpdateDepositStatus_Result()
        {
        }
        
        public UpdateDepositStatus_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostPESALinkDeposits", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class PostPESALinkDeposits
    {
        
        public PostPESALinkDeposits()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostPESALinkDeposits_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", IsWrapped=true)]
    public partial class PostPESALinkDeposits_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PESALinkTransfer", Order=0)]
        public string return_value;
        
        public PostPESALinkDeposits_Result()
        {
        }
        
        public PostPESALinkDeposits_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface PESALinkTransfer_PortChannel : WebRef.PESALinkTransfer_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class PESALinkTransfer_PortClient : System.ServiceModel.ClientBase<WebRef.PESALinkTransfer_Port>, WebRef.PESALinkTransfer_Port
    {
        public string serviceEndpoint { get; internal set; }
        public bool PreAuthenticate { get; internal set; }
        public NetworkCredential clientCredentials { get; internal set; }

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PESALinkTransfer_PortClient() : 
                base(PESALinkTransfer_PortClient.GetDefaultBinding(), PESALinkTransfer_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PESALinkTransfer_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PESALinkTransfer_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(PESALinkTransfer_PortClient.GetBindingForEndpoint(endpointConfiguration), PESALinkTransfer_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PESALinkTransfer_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PESALinkTransfer_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PESALinkTransfer_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PESALinkTransfer_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PESALinkTransfer_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRef.GetEntryToTransfer_Result> WebRef.PESALinkTransfer_Port.GetEntryToTransferAsync(WebRef.GetEntryToTransfer request)
        {
            return base.Channel.GetEntryToTransferAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRef.GetEntryToTransfer_Result> GetEntryToTransferAsync()
        {
            WebRef.GetEntryToTransfer inValue = new WebRef.GetEntryToTransfer();
            return ((WebRef.PESALinkTransfer_Port)(this)).GetEntryToTransferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRef.UpdateTransferStatus_Result> WebRef.PESALinkTransfer_Port.UpdateTransferStatusAsync(WebRef.UpdateTransferStatus request)
        {
            return base.Channel.UpdateTransferStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRef.UpdateTransferStatus_Result> UpdateTransferStatusAsync(string requestID, string statusOfRequestCode)
        {
            WebRef.UpdateTransferStatus inValue = new WebRef.UpdateTransferStatus();
            inValue.requestID = requestID;
            inValue.statusOfRequestCode = statusOfRequestCode;
            return ((WebRef.PESALinkTransfer_Port)(this)).UpdateTransferStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRef.GetEntryToSeekStatus_Result> WebRef.PESALinkTransfer_Port.GetEntryToSeekStatusAsync(WebRef.GetEntryToSeekStatus request)
        {
            return base.Channel.GetEntryToSeekStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRef.GetEntryToSeekStatus_Result> GetEntryToSeekStatusAsync()
        {
            WebRef.GetEntryToSeekStatus inValue = new WebRef.GetEntryToSeekStatus();
            return ((WebRef.PESALinkTransfer_Port)(this)).GetEntryToSeekStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRef.GetISODescription_Result> WebRef.PESALinkTransfer_Port.GetISODescriptionAsync(WebRef.GetISODescription request)
        {
            return base.Channel.GetISODescriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRef.GetISODescription_Result> GetISODescriptionAsync(string actionCode)
        {
            WebRef.GetISODescription inValue = new WebRef.GetISODescription();
            inValue.actionCode = actionCode;
            return ((WebRef.PESALinkTransfer_Port)(this)).GetISODescriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRef.CheckValidAccountDetails_Result> WebRef.PESALinkTransfer_Port.CheckValidAccountDetailsAsync(WebRef.CheckValidAccountDetails request)
        {
            return base.Channel.CheckValidAccountDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRef.CheckValidAccountDetails_Result> CheckValidAccountDetailsAsync(string accountNo)
        {
            WebRef.CheckValidAccountDetails inValue = new WebRef.CheckValidAccountDetails();
            inValue.accountNo = accountNo;
            return ((WebRef.PESALinkTransfer_Port)(this)).CheckValidAccountDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRef.InsertDepositEntry_Result> WebRef.PESALinkTransfer_Port.InsertDepositEntryAsync(WebRef.InsertDepositEntry request)
        {
            return base.Channel.InsertDepositEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRef.InsertDepositEntry_Result> InsertDepositEntryAsync(string sourceReferenceNo, string sourceBankCode, string sourceAccountNo, string sourceAccountName, string purpose, string amountToTransfer, string destinationAccountNo)
        {
            WebRef.InsertDepositEntry inValue = new WebRef.InsertDepositEntry();
            inValue.sourceReferenceNo = sourceReferenceNo;
            inValue.sourceBankCode = sourceBankCode;
            inValue.sourceAccountNo = sourceAccountNo;
            inValue.sourceAccountName = sourceAccountName;
            inValue.purpose = purpose;
            inValue.amountToTransfer = amountToTransfer;
            inValue.destinationAccountNo = destinationAccountNo;
            return ((WebRef.PESALinkTransfer_Port)(this)).InsertDepositEntryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRef.GetEntryToSeekDepositStatus_Result> WebRef.PESALinkTransfer_Port.GetEntryToSeekDepositStatusAsync(WebRef.GetEntryToSeekDepositStatus request)
        {
            return base.Channel.GetEntryToSeekDepositStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRef.GetEntryToSeekDepositStatus_Result> GetEntryToSeekDepositStatusAsync()
        {
            WebRef.GetEntryToSeekDepositStatus inValue = new WebRef.GetEntryToSeekDepositStatus();
            return ((WebRef.PESALinkTransfer_Port)(this)).GetEntryToSeekDepositStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRef.UpdateDepositStatus_Result> WebRef.PESALinkTransfer_Port.UpdateDepositStatusAsync(WebRef.UpdateDepositStatus request)
        {
            return base.Channel.UpdateDepositStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRef.UpdateDepositStatus_Result> UpdateDepositStatusAsync(string entryNo, string sourceReferenceNo, string sourceBankCode, string sourceAccountNo, string amountToTransfer, string destinationAccountNo, string responseCode)
        {
            WebRef.UpdateDepositStatus inValue = new WebRef.UpdateDepositStatus();
            inValue.entryNo = entryNo;
            inValue.sourceReferenceNo = sourceReferenceNo;
            inValue.sourceBankCode = sourceBankCode;
            inValue.sourceAccountNo = sourceAccountNo;
            inValue.amountToTransfer = amountToTransfer;
            inValue.destinationAccountNo = destinationAccountNo;
            inValue.responseCode = responseCode;
            return ((WebRef.PESALinkTransfer_Port)(this)).UpdateDepositStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRef.PostPESALinkDeposits_Result> WebRef.PESALinkTransfer_Port.PostPESALinkDepositsAsync(WebRef.PostPESALinkDeposits request)
        {
            return base.Channel.PostPESALinkDepositsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRef.PostPESALinkDeposits_Result> PostPESALinkDepositsAsync()
        {
            WebRef.PostPESALinkDeposits inValue = new WebRef.PostPESALinkDeposits();
            return ((WebRef.PESALinkTransfer_Port)(this)).PostPESALinkDepositsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PESALinkTransfer_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PESALinkTransfer_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://navtest.stima-sacco.local:2022/NAVTEST/WS/STIMASACCO/Codeunit/PESALinkTran" +
                        "sfer");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PESALinkTransfer_PortClient.GetBindingForEndpoint(EndpointConfiguration.PESALinkTransfer_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PESALinkTransfer_PortClient.GetEndpointAddress(EndpointConfiguration.PESALinkTransfer_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            PESALinkTransfer_Port,
        }
    }
}
